name: pivariety-streaming-demo
base: core24
version: "0.1"
summary: Raspberry Pi camera streaming demo
description: A demo for streaming video from a Raspberry Pi camera using Snap.
grade: stable
confinement: strict

plugs:
  system-files:
    write:
      - /sys/kernel/config/device-tree/overlays

parts:
  pivariety-sdk:
    plugin: nil
    override-pull: |
      curl -s --compressed "https://arducam.github.io/arducam_ppa/KEY.gpg" | apt-key add -
      curl -s --compressed -o /etc/apt/sources.list.d/arducam_list_files.list "https://arducam.github.io/arducam_ppa/arducam_list_files.list"
      apt update
      apt install arducam-pivariety-sdk-dev
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/
      cp /usr/lib/libarducam_pivariety* $SNAPCRAFT_PART_INSTALL/lib/

  picamera:
    after: [pivariety-sdk]
    plugin: python
    source: .
    build-packages:
      - git
      - patch
      - python3-dev
      - python3-venv
      - pkg-config
      - pybind11-dev
      - libcap-dev
      - meson
      - ninja-build
      - libssl-dev
      - openssl
      - cmake
      - libfmt-dev
      - libdrm-dev
    python-packages:
      - jinja2
      - pyyaml
      - ply
    stage-packages:
      - libfmt-dev
    build-environment:
      - PKG_CONFIG_PATH: "$SNAPCRAFT_PART_INSTALL/lib/pkgconfig"
      - LD_LIBRARY_PATH: "$SNAPCRAFT_PART_INSTALL/lib/python3.12/site-packages/libcamera:$SNAPCRAFT_PART_INSTALL/lib"
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_PART_INSTALL/bin/pip list
      export PYTHON=$SNAPCRAFT_PART_INSTALL/bin/python3
      cd $SNAPCRAFT_PART_SRC
      git clone https://github.com/ArduCAM/libcamera.git
      cd libcamera
      meson setup build --buildtype=release -Dpipelines=rpi/vc4,rpi/pisp -Dipas=rpi/vc4,rpi/pisp -Dgstreamer=disabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled -Dlibdir=lib --prefix=$SNAPCRAFT_PART_INSTALL/
      ninja -C build install
      cd ..
      find $SNAPCRAFT_PART_INSTALL -name jinja2
      $SNAPCRAFT_PART_INSTALL/bin/python3 -c "import libcamera"
      git clone https://github.com/tomba/kmsxx.git
      cd kmsxx
      meson setup build --buildtype=release --prefix=$SNAPCRAFT_PART_INSTALL -Dpykms=enabled -Dlibdir=lib
      ninja -C build install
      cd ..
      $SNAPCRAFT_PART_INSTALL/bin/python3 -m pip install picamera2
      $SNAPCRAFT_PART_INSTALL/bin/python3 -c "import picamera2; from libcamera import Transform"
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/pistream $SNAPCRAFT_PART_INSTALL/bin/
      find /root -name libfmt.so.9
    stage:
      - bin/pistream
      - lib/*
      - usr/lib/aarch64-linux-gnu/*
      - share/libcamera/ipa*

  overlay:
    plugin: nil
    source: .
    build-packages:
      - device-tree-compiler
    override-build: |
      dtc -@ -I dts -O dtb -o imx477.dtbo ./overlays/imx477-overlay.dts
      mkdir -p $SNAPCRAFT_PART_INSTALL/overlays
      cp imx477.dtbo $SNAPCRAFT_PART_INSTALL/overlays/
    stage:
      - imx477.dtbo

  scripts:
    plugin: dump
    source: bin
    organize:
      load-overlay.sh: bin/load-overlay

apps:
  load-overlay:
    command: bin/load-overlay
    daemon: oneshot
    plugs:
      - system-files

  pivariety-streaming-demo:
    command: bin/pistream
    daemon: simple
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/python3.12/site-packages/libcamera:$SNAP/usr/lib/aarch64-linux-gnu"
      PYTHONPATH: "$PYTHONPATH:$SNAP/lib/python3.12/site-packages"
      LIBCAMERA_IPA_MODULE_PATH: "$SNAP/lib/libcamera"
      LIBCAMERA_RPI_TUNING_FILE: "$SNAP/share/libcamera/ipa/rpi/pisp/imx477.json"
    plugs:
      - mount-observe
      - network
      - network-bind
      - opengl
      - hardware-observe